name: venatronics_llc_challenge
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  http: ^1.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
